# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test & Build

on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: npm install and build 
      run: |
        npm ci
        npm run build:ci
    - uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: dist/
        
  test:
    runs-on: ubuntu-latest
    needs: build
    
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: artifacts
        path: dist
        
    - name: Debug
      run: echo "Current branch is $GITHUB_REF"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'      
    - name: npm install and test
      run: |
        npm ci
        npm run test:ci

    
